name: Alura Stats Update

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Update Alura Stats
        uses: vitorvgs/alura-stats-action@v1.0
        with:
          alura_username: vdfs89 
          alura_token: ${{ secrets.ALURA_TOKEN }}
          
